### ISSUE TITLE
Discord bot problem

### ISSUE THREAD

**Issue by WanderRainID** [InnateAlpaca/BedrockBridge#2]
The bot keep sending messages to the text channel on discord when user running command with custom prefix from other behavior pack. Example like when type +tpa <player> (tpa is command for teleporting between player) the discord bot also send this to the text channel on discord

**Comment by InnateAlpaca** [comment]
Hello, we solved the issue on discord. Just answering here too for the others.

BedrockBridge can't know what prefixes are other packs using, hence will log all those messages. It is though possible to add an easy plugin that will block all messages starting with certain prefixes from being sent to discord.

Here an example of how this can be implemented. You can replace this inside `BedrockBridge/options/customise.js`. This will prevent messages starting with `+` or `!` from being sent to discord!
```js
const upStreamMessage = async (player, message)=>{
    if (!message.startsWith('+') && !message.startsWith('!'))
        return {
            author: player.nick,
            text: message
        }   
}
```
