### ISSUE TITLE
SyntaxError 

### ISSUE THREAD

**Issue by GuyyaReiki** [InnateAlpaca/BedrockBridge#5]
[Scripting] Plugin [Bedrock-Bridge v1.3.9 - 1.3.9] - [main.js] ran with error: [SyntaxError: Could not find export 'Vector' in module '@minecraft/server']

**Comment by InnateAlpaca** [comment]
Hello, can you provide more context about when this error happened? Was it at startup or later on?

**Comment by InnateAlpaca** [comment]
Alright, the issue was caused by a bridge-plugins: "Basic Warps". Please replace the plugin files with the fixed one which we published today [on github](https://github.com/InnateAlpaca/BedrockBridge/tree/main/bridge_plugins/basicWarps)

**Comment by GuyyaReiki** [comment]
ok thx
